version: '2'
services:
    vpltreeviewapplication-app:
        image: vpltreeviewapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vpltreeviewapplication-mysql:3306/vpltreeviewapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://vpltreeviewapplication-elasticsearch:9200
        ports:
            - 8080:8080
    vpltreeviewapplication-mysql:
        extends:
            file: mysql.yml
            service: vpltreeviewapplication-mysql
    vpltreeviewapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: vpltreeviewapplication-elasticsearch
